Changed configure.in so it can import rdkafka from any location. Now you can specify kafka location using --with-kafka-* params configure params.

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -146,30 +146,44 @@ else
     AC_MSG_RESULT(no)
 fi
 
-AC_MSG_CHECKING(for rdkafka libraries)
+AC_ARG_WITH(rdkafka_includes,
+        [  --with-rdkafka-includes=DIR    rdkafka include directory],
+        [with_rdkafka_includes="$withval"],[with_rdkafka_includes="no"])
+
+AC_ARG_WITH(rdkafka_libraries,
+        [  --with-rdkfaka-libraries=DIR   rdkafka library directory],
+        [with_rdkafka_libraries="$withval"],[with_rdkafka_libraries="no"])
+
+if test "x$with_rdkafka_includes" != "x"; then
+  CFLAGS="${CFLAGS} -I${with_rdkafka_includes}"
+fi
+
+if test "x$with_rdkafka_libraries" != "xno"; then
+  LDFLAGS="${LDFLAGS}  -L${with_rdkafka_libraries}"
+fi
+
 AC_ARG_ENABLE(kafka,
 [  --enable-kafka           Enable kafka messagin.],
        enable_kafka="$enableval", enable_kafka="no")
-if test "x$enable_kafka" = "xyes"; then
-    AC_CHECK_HEADERS([librdkafka/rdkafka.h],[],
+
+if test "x$enable_kafka" = "x$enableval"; then
+  AC_CHECK_HEADERS([librdkafka/rdkafka.h],[],
       [
         echo "Error: Librdkafka headers not found."
         echo "You can download and install it from https://github.com/edenhill/librdkafka"
         echo "Remember you have to use 0.7 branch"
         exit 1
       ])
-    AC_CHECK_LIB(rdkafka,rd_kafka_new,[],
-      [
-        echo "Error: Librdkafka library not found."
-        echo "You can download and install it from https://github.com/edenhill/librdkafka"
-        echo "Remember you have to use 0.7 branch"
-        exit 1
-      ])
-    AC_DEFINE([HAVE_RDKAFKA],[],[Have Apache Kafka library])
-    LDFLAGS="$LDFLAGS -lrdkafka"
-    AC_MSG_RESULT(yes)
-else
-    AC_MSG_RESULT(no)
+
+  AC_CHECK_LIB(rdkafka,rd_kafka_new,[],
+    [
+      echo "Error: Librdkafka library not found."
+      echo "You can download and install it from https://github.com/edenhill/librdkafka"
+      echo "Remember you have to use 0.7 branch"
+      exit 1
+    ])
+  
+  AC_DEFINE([HAVE_RDKAFKA],[],[Have Apache Kafka library])
 fi
 
 
