updated: echidna plugin now supports hashes for event and session correlation.

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -1043,7 +1043,15 @@ AC_ARG_ENABLE(plugin-echidna,
        enable_plugin_echidna="$enableval", enable_plugin_echidna="no")
 if test "x$enable_plugin_echidna" = "xyes"; then
     CPPFLAGS="$CPPFLAGS -DENABLE_PLUGIN_ECHIDNA"
-    LIBS="$LIBS -lwebsockets -ljson -lcurl"
+    LIBS="$LIBS -lwebsockets -ljson -lcurl -lcrypto"
+
+    AC_CHECK_LIB(crypto, SHA256_Init,, LCRYPTO="no")
+    if test "x$LCRYPTO" = "xno"; then
+        echo
+        echo "   ERROR!  libcrypto not found!"
+        echo
+        exit 1
+    fi
 
     AC_CHECK_LIB(curl, curl_easy_setopt,, LCURL="no")
     if test "x$LCURL" = "xno"; then
