IP packets length and ethernet packets length are now aggregated in groups. Priority_name added.

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -199,6 +199,44 @@ if test "x$enable_kafka" = "x$enableval"; then
   LDFLAGS="${LDFLAGS} -lrdkafka"  
 fi
 
+AC_ARG_WITH(rd_includes,
+        [  --with-rd-includes=DIR    rd include directory],
+        [with_rd_includes="$withval"],[with_rd_includes="no"])
+
+AC_ARG_WITH(rd_libraries,
+        [  --with-rdkfaka-libraries=DIR   rd library directory],
+        [with_rd_libraries="$withval"],[with_rd_libraries="no"])
+
+if test "x$with_rd_includes" != "xno"; then
+  CFLAGS="${CFLAGS} -I${with_rd_includes}"
+fi
+
+if test "x$with_rd_libraries" != "xno"; then
+  LDFLAGS="${LDFLAGS}  -L${with_rd_libraries}"
+fi
+
+AC_ARG_ENABLE(rd,
+[  --enable-rd           Enable librd extensions.],
+       enable_rd="$enableval", enable_rd="no")
+
+if test "x$enable_rd" = "x$enableval"; then
+  AC_CHECK_HEADERS([librd/rd.h],[],
+      [
+        echo "Error: Librd headers not found."
+        echo "You can download and install it from https://github.com/edenhill/librd"
+        exit 1
+      ])
+
+  AC_CHECK_LIB(rd,rd_init,[],
+    [
+      echo "Error: Librd library not found."
+      echo "You can download and install it from https://github.com/edenhill/librd"
+      exit 1
+    ])
+
+  LDFLAGS="${LDFLAGS} -lrd"  
+fi
+
 
 # AC_PROG_YACC defaults to "yacc" when not found
 # this check defaults to "none"
