Adding rbhttp library in the configure flags

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -247,6 +247,26 @@ if test "x$enable_kafka" = "x$enableval"; then
   LDFLAGS="${LDFLAGS} -lrdkafka"  
 fi
 
+AC_ARG_ENABLE(rb-http,
+[  --enable-rb-http         Enable HTTP POST json sending.],
+       enable_rbhttp="$enableval", enable_rbhttp="no")
+
+if test "x$enable_rbhttp" = "x$enableval"; then
+  AC_CHECK_HEADERS([librbhttp/librb-http.h],[],
+      [
+        echo "Error: redBorder HTTP headers not found."
+        exit 1
+      ])
+
+  AC_CHECK_LIB(rbhttp,rb_http_produce,[],
+    [
+      echo "Error: redBorder HTTP library not found."
+      exit 1
+    ])
+
+  LDFLAGS="${LDFLAGS} -lrbhttp"
+fi
+
 AC_ARG_WITH(rd_includes,
         [  --with-rd-includes=DIR    rd include directory],
         [with_rd_includes="$withval"],[with_rd_includes="no"])
