updated: platypus plugin renamed to echidna and aligned to the new command and sumbmission protocols.

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -1035,6 +1035,41 @@ if test "$with_tcl" != "no"; then
     fi
 fi
 
+#
+# OUTPUT PLUGIN - ECHIDNA
+
+AC_ARG_ENABLE(plugin-echidna,
+[  --enable-plugin-echidna           Enable echidna plugin (experimental)],
+       enable_plugin_echidna="$enableval", enable_plugin_echidna="no")
+if test "x$enable_plugin_echidna" = "xyes"; then
+    CPPFLAGS="$CPPFLAGS -DENABLE_PLUGIN_ECHIDNA"
+    LIBS="$LIBS -lwebsockets -ljson -lcurl"
+
+    AC_CHECK_LIB(curl, curl_easy_setopt,, LCURL="no")
+    if test "x$LCURL" = "xno"; then
+        echo
+        echo "   ERROR!  libcurl not found!"
+        echo
+        exit 1
+    fi
+
+    AC_CHECK_LIB(websockets, libwebsocket_create_context,, LWEBSOCKETS="no")
+    if test "x$LWEBSOCKETS" = "xno"; then
+        echo
+        echo "   ERROR!  libwebsockets not found."
+        echo
+        exit 1
+    fi
+
+    AC_CHECK_LIB(json, json_tokener_parse,, LJSON="no")
+    if test "x$LJSON" = "xno"; then
+        echo
+        echo "   ERROR!  libjson not found."
+        echo
+        exit 1
+    fi
+
+fi
 
 
 # let's make some fixes..
